### ISSUE TITLE
Debug error: "World Scripter script pack missing"

### ISSUE THREAD

**Issue by Avera9eJoe** [Kekilla0/World-Scripter#7]
I am getting a debug error when attempting to add a macro to the world scripter compendium:
![image](https://user-images.githubusercontent.com/5304201/185247227-2f08dc99-6fd2-40b0-a2b9-f354f21a04aa.png)
![image](https://user-images.githubusercontent.com/5304201/185247258-d37a4c3f-635c-475e-bb45-41522a31199c.png)
![image](https://user-images.githubusercontent.com/5304201/185247280-0e7116ba-d3e5-4021-829b-1f18efa73ca3.png)

**Steps to reproduce:**
1. Create macro
2. Right click --> 'Add to World Scripter Compendium'
3. Observe the debug error

**Comment by davelacorneille** [comment]
A quick fix that I did for this bug:
I've created a folder and an empty file in "\FoundryData\Data\modules\world-scripter\packs\wsMacros.db"

I wanted to share my world-script with all my worlds automatically, so I created the file in the module instead of the worlds folder: "yourWorld\packs\wsMacros.db".

**Comment by trioderegion** [comment]
Be careful about storing data inside a module folder, as it will get wiped on update.

This bug has been chased for multiple versions now 😅 . I'll get it addressed for v10.

The intention is for the module to automatically create a world compendium if it doesn't exist.

**Comment by davelacorneille** [comment]
Yes thank you, great advice.

I've set no update for now.

Would be great if we can have a shared db. One per world and one to share
between all worlds!

😇

**Comment by Avera9eJoe** [comment]
Ah gotcha! So it's something known 👍

In the meantime what I did was creat a custom json file (worldscripts.js) inside of my world folder, and then I added the filename to the "scripts" line inside the world's json file. To make world scripts I just add the macros to that file
