### ISSUE TITLE
Execute on Ready

### ISSUE THREAD

**Issue by mech-tools** [Kekilla0/World-Scripter#9]
Hello,

World scripts have the ability to be executed on "ready" hook.
Can this module do the same?

**Comment by trioderegion** [comment]
Yes, all world scripter compendium macros are actually run inside of the 'ready' hook, so you dont need to add anything special.

You cannot use hooks earlier than `ready` and you need to use the `Hooks.on` calls for hooks AFTER `ready`.

**Comment by mech-tools** [comment]
@trioderegion Ok, understood.
Note: "canvasReady" is probably called after "ready" but before macro executions.
